#!/usr/bin/env bash
# scripts/state/init-project.sh — scaffold ClaudeHut project state.
#
# Bridges plugin source to native Claude Code primitives:
#  - copies <plugin>/rules/**/*.md into <project>/.claude/rules/ so Claude's
#    native loader picks them up on file-glob match (per rule's `paths:` frontmatter)
#  - writes a thin <project>/.claude/CLAUDE.md that @imports memory files
#  - scaffolds <project>/.claudehut/ for workflow state (specs/plans/findings/learnings)
#
# Flags:
#   --refresh    overwrite rule copies whose SHA256 matches the previously-recorded
#                checksum (i.e. files the user has NOT edited). User-modified rules
#                are reported and left alone unless --force is also passed.
#   --force      with --refresh, overwrite even user-modified rules.
set -euo pipefail

REFRESH=0
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --refresh) REFRESH=1 ;;
    --force)   FORCE=1   ;;
    -h|--help)
      sed -n '2,18p' "$0"; exit 0 ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"

_find_plugin_root() {
  if [[ -n "${CLAUDE_PLUGIN_ROOT:-}" ]]; then echo "$CLAUDE_PLUGIN_ROOT"; return; fi
  local d
  d="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd -P)"
  while [[ "$d" != "/" && -n "$d" ]]; do
    [[ -f "$d/.claude-plugin/plugin.json" ]] && { echo "$d"; return; }
    d="$(dirname "$d")"
  done
  echo "error: cannot locate ClaudeHut plugin root (no .claude-plugin/plugin.json found upward)" >&2
  exit 1
}
PLUGIN_ROOT="$(_find_plugin_root)"

CLAUDEHUT_DIR="$PROJECT_ROOT/.claudehut"
CLAUDE_DIR="$PROJECT_ROOT/.claude"
RULES_DST="$CLAUDE_DIR/rules"

MODE="init"
if [[ -d "$CLAUDEHUT_DIR" ]] && (( REFRESH == 0 )); then
  MODE="repair"
  echo "claudehut: .claudehut/ already exists — running in REPAIR mode (creates missing only)"
fi
(( REFRESH == 1 )) && MODE="refresh"

mkdir -p \
  "$CLAUDEHUT_DIR/memory" \
  "$CLAUDEHUT_DIR/specs" \
  "$CLAUDEHUT_DIR/plans" \
  "$CLAUDEHUT_DIR/findings" \
  "$CLAUDEHUT_DIR/reuse-scans" \
  "$CLAUDE_DIR" \
  "$RULES_DST"

copy_if_missing() {
  local src="$1" dst="$2"
  if [[ ! -f "$dst" ]]; then
    cp "$src" "$dst"
    echo "claudehut: created $dst"
  fi
}

# ---- Templates → .claudehut/ -----------------------------------------------
copy_if_missing "$PLUGIN_ROOT/templates/claudehut-config.template.json" "$CLAUDEHUT_DIR/claudehut-config.json"
copy_if_missing "$PLUGIN_ROOT/templates/stack-signals.template.md"     "$CLAUDEHUT_DIR/memory/stack-signals.md"
copy_if_missing "$PLUGIN_ROOT/templates/conventions.template.md"       "$CLAUDEHUT_DIR/memory/conventions.md"
copy_if_missing "$PLUGIN_ROOT/templates/index.template.md"             "$CLAUDEHUT_DIR/memory/index.md"

[[ -f "$CLAUDEHUT_DIR/memory/learnings.jsonl"     ]] || : > "$CLAUDEHUT_DIR/memory/learnings.jsonl"
[[ -f "$CLAUDEHUT_DIR/memory/learnings-recent.md" ]] || cat > "$CLAUDEHUT_DIR/memory/learnings-recent.md" <<'LR_EOF'
# Recent Learnings

> Auto-regenerated by the `learn` skill at the end of each task from the
> top-N most-recent entries in `learnings.jsonl`. CLAUDE.md @imports this
> file, so it shows up in every Claude Code session.

(none yet — finish a task to populate)
LR_EOF
[[ -f "$CLAUDEHUT_DIR/memory/reusable-impl-map.json" ]] || : > "$CLAUDEHUT_DIR/memory/reusable-impl-map.json"

# ---- Stack-aware rule copy: <plugin>/rules → <project>/.claude/rules -------
# A rule's optional `stack:` frontmatter constrains which projects it applies to
# (e.g. `stack: "web=webflux"`). We parse the user's detected stack from
# .claudehut/memory/stack-signals.md and skip rules whose constraint contradicts.
# Format we look for in stack-signals.md: lines like `- key: value`.

STACK_FILE="$CLAUDEHUT_DIR/memory/stack-signals.md"
_stack_value() {
  # $1 = key (e.g. "web"). Echoes the value from stack-signals.md, or "unknown".
  local k="$1"
  grep -E "^- ${k}:" "$STACK_FILE" 2>/dev/null \
    | head -1 \
    | sed -E "s/^- ${k}:[[:space:]]*//; s/[[:space:]]*#.*//; s/[[:space:]]+$//" \
    || true
}

_rule_matches_stack() {
  # $1 = path to plugin rule .md. Reads its `stack:` frontmatter (if any) and
  # returns 0 if the rule applies to this project, 1 if it should be skipped.
  local rule="$1"
  local constraint
  constraint="$(awk '
    /^---[[:space:]]*$/ { n++; if (n==2) exit }
    n==1 && /^stack:/ {
      sub(/^stack:[[:space:]]*"?/, "")
      sub(/"?[[:space:]]*$/, "")
      print
      exit
    }
  ' "$rule")"
  [[ -z "$constraint" ]] && return 0  # no constraint → universally applicable

  local key="${constraint%%=*}"
  local want="${constraint#*=}"
  local have
  have="$(_stack_value "$key")"
  [[ -z "$have" || "$have" == "unknown" ]] && return 1  # unknown stack → skip stack-conditional rules until detected
  [[ "$have" == "$want" ]]
}

# Per-rule checksum file lets `--refresh` distinguish user-edited rules from pristine copies.
CHECKSUMS="$RULES_DST/.checksums.json"
[[ -f "$CHECKSUMS" ]] || echo '{}' > "$CHECKSUMS"

_sha256() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}';
  else sha256sum "$1" | awk '{print $1}'; fi
}

copied=0; skipped_stack=0; refreshed=0; user_modified=0
while IFS= read -r src; do
  rel="${src#$PLUGIN_ROOT/rules/}"
  dst="$RULES_DST/$rel"
  if ! _rule_matches_stack "$src"; then
    skipped_stack=$((skipped_stack+1))
    # On refresh, also clean up a previously-copied rule whose stack no longer matches.
    if (( REFRESH == 1 )) && [[ -f "$dst" ]]; then
      rm "$dst"
      echo "claudehut: removed $rel (stack no longer matches)"
    fi
    continue
  fi
  mkdir -p "$(dirname "$dst")"
  if [[ ! -f "$dst" ]]; then
    cp "$src" "$dst"
    recorded="$(_sha256 "$dst")"
    CHECKSUMS_TMP="$(jq --arg k "$rel" --arg v "$recorded" '. + {($k): $v}' "$CHECKSUMS")"
    printf '%s' "$CHECKSUMS_TMP" > "$CHECKSUMS"
    copied=$((copied+1))
  elif (( REFRESH == 1 )); then
    current_dst="$(_sha256 "$dst")"
    recorded="$(jq -r --arg k "$rel" '.[$k] // ""' "$CHECKSUMS")"
    if [[ -n "$recorded" && "$current_dst" != "$recorded" ]] && (( FORCE == 0 )); then
      echo "claudehut: [warn] user-modified $rel — skipping (pass --force to overwrite)"
      user_modified=$((user_modified+1))
      continue
    fi
    cp "$src" "$dst"
    new_sum="$(_sha256 "$dst")"
    CHECKSUMS_TMP="$(jq --arg k "$rel" --arg v "$new_sum" '. + {($k): $v}' "$CHECKSUMS")"
    printf '%s' "$CHECKSUMS_TMP" > "$CHECKSUMS"
    refreshed=$((refreshed+1))
  fi
done < <(find "$PLUGIN_ROOT/rules" -type f -name '*.md')

# ---- Augment .claude/CLAUDE.md (idempotent, backup/restore-safe) ----------
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
CLAUDEHUT_SECTION_MARKER="<!-- claudehut-managed-section -->"
CLAUDEHUT_END_MARKER="<!-- /claudehut-managed-section -->"
CLAUDE_BACKUP="$CLAUDEHUT_DIR/.claude-md.backup"
CLAUDEHUT_BLOCK="$(cat "$PLUGIN_ROOT/templates/claude-md.template.md")"

[[ -f "$CLAUDE_MD" ]] && cp "$CLAUDE_MD" "$CLAUDE_BACKUP"

if [[ -f "$CLAUDE_MD" ]]; then
  if grep -q "$CLAUDEHUT_SECTION_MARKER" "$CLAUDE_MD"; then
    echo "claudehut: CLAUDE.md plugin section already present; skipping"
  else
    printf '\n%s\n' "$CLAUDEHUT_BLOCK" >> "$CLAUDE_MD"
    echo "claudehut: appended plugin section to existing $CLAUDE_MD"
  fi
elif [[ -f "$CLAUDE_BACKUP" ]]; then
  cp "$CLAUDE_BACKUP" "$CLAUDE_MD"
  grep -q "$CLAUDEHUT_SECTION_MARKER" "$CLAUDE_MD" || printf '\n%s\n' "$CLAUDEHUT_BLOCK" >> "$CLAUDE_MD"
  echo "claudehut: restored $CLAUDE_MD from backup"
else
  printf '%s\n' "$CLAUDEHUT_BLOCK" > "$CLAUDE_MD"
  cp "$CLAUDE_MD" "$CLAUDE_BACKUP"
  echo "claudehut: created $CLAUDE_MD with plugin section only"
fi

# ---- .gitignore patches ---------------------------------------------------
GI="$PROJECT_ROOT/.gitignore"
[[ -f "$GI" ]] || touch "$GI"
if ! grep -q '^.claudehut/reuse-scans/' "$GI" 2>/dev/null; then
  cat >> "$GI" <<'EOF'

# ClaudeHut plugin — runtime ephemeral files
.claudehut/reuse-scans/
.claudehut/findings/*.tmp
.claudehut/.tmp/
EOF
  echo "claudehut: appended .gitignore patches"
fi

# ---- Summary --------------------------------------------------------------
echo ""
case "$MODE" in
  init)    echo "ClaudeHut initialized at: $CLAUDEHUT_DIR" ;;
  repair)  echo "ClaudeHut REPAIR complete at: $CLAUDEHUT_DIR" ;;
  refresh) echo "ClaudeHut REFRESH complete at: $CLAUDEHUT_DIR" ;;
esac
echo ""
echo "Rules:"
echo "  copied to $RULES_DST: $copied"
(( refreshed     > 0 )) && echo "  refreshed: $refreshed"
(( user_modified > 0 )) && echo "  user-modified (left alone): $user_modified"
(( skipped_stack > 0 )) && echo "  skipped (stack mismatch): $skipped_stack"
echo ""
echo "Project layout:"
echo "  .claude/CLAUDE.md            ← thin file with @imports"
echo "  .claude/rules/               ← rules auto-loaded by Claude on path match"
echo "  .claude/rules/.checksums.json ← used by 'init --refresh'"
echo "  .claudehut/memory/           ← conventions + learnings + stack signals"
echo "  .claudehut/{specs,plans,findings}/ ← per-task workflow artifacts"
echo "  .claudehut/.claude-md.backup ← backup if CLAUDE.md is ever deleted"
echo ""
echo "Next steps:"
echo "  1. Edit .claudehut/memory/stack-signals.md to set web/orm/messaging/etc."
echo "     (or let the SessionStart hook auto-detect on next session)."
echo "  2. Re-run /claudehut:init --refresh after detection to bring in stack-specific rules."
echo "  3. Edit .claudehut/memory/conventions.md with team-specific conventions."
echo "  4. Commit .claude/ + .claudehut/ + .gitignore to source control."
