#!/usr/bin/env bash
# regenerate-recent.sh [N]
#
# Rebuild .claudehut/memory/learnings-recent.md from the top-N most-recent
# entries in learnings.jsonl. Called as the final step of the claudehut:learn
# pipeline. CLAUDE.md @imports learnings-recent.md, and the phase dispatch
# prompts emit it, so this file is the working-memory channel for every phase.
#
# Safe when learnings.jsonl is absent/empty/corrupt -> writes the canonical
# "(none yet)" stub (byte-identical to the init seed, so a fresh project diffs
# clean). Bash 3.2 / POSIX-awk safe; jq required.
set -euo pipefail

N="${1:-20}"
case "$N" in
  ''|*[!0-9]*) echo "error: N must be a non-negative integer, got: $N" >&2; exit 2 ;;
esac

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
LEARNINGS="$PROJECT_ROOT/.claudehut/memory/learnings.jsonl"
RECENT="$PROJECT_ROOT/.claudehut/memory/learnings-recent.md"
TMP="$(mktemp)"

HEADER='# Recent Learnings

> Auto-regenerated by the `learn` skill at the end of each task from the
> top-N most-recent entries in `learnings.jsonl`. CLAUDE.md @imports this
> file, so it shows up in every Claude Code session.'

_write_stub() {
  printf '%s\n\n(none yet — finish a task to populate)\n' "$HEADER" > "$TMP"
  mv "$TMP" "$RECENT"
}

# Absent / empty / zero parseable entries -> stub.
if [[ ! -s "$LEARNINGS" ]]; then
  _write_stub; echo "regenerate-recent: no entries — wrote stub"; exit 0
fi
count="$(jq -s 'length' "$LEARNINGS" 2>/dev/null || echo 0)"
if [[ "$count" -eq 0 ]]; then
  _write_stub; echo "regenerate-recent: no parseable entries — wrote stub"; exit 0
fi

# Sort by .ts (ISO-8601-UTC sorts lexicographically == chronologically), newest
# first; take N. Render references only — never raw secret-bearing content.
jq -rs --argjson n "$N" '
  sort_by(.ts // "") | reverse | .[0:$n][]
  | "- **\(.category // "uncategorized")** — \(.title // "(untitled)") `\(.task_id // "?")`"
    + (if ((.tags // []) | length) > 0
         then " _[" + ((.tags // []) | join(", ")) + "]_"
         else "" end)
' "$LEARNINGS" > "${TMP}.bullets" 2>/dev/null || true

if [[ ! -s "${TMP}.bullets" ]]; then
  rm -f "${TMP}.bullets"
  _write_stub; echo "regenerate-recent: jq produced no output — wrote stub"; exit 0
fi

{ printf '%s\n\n' "$HEADER"; cat "${TMP}.bullets"; } > "$TMP"
rm -f "${TMP}.bullets"
mv "$TMP" "$RECENT"
echo "regenerate-recent: wrote $RECENT ($(grep -c '^- \*\*' "$RECENT" | tr -d ' ') entries)"
