#!/usr/bin/env bash
# reindex.sh — regenerate .claudehut/memory/index.md from source classes + learnings
set -euo pipefail

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
INDEX="$PROJECT_ROOT/.claudehut/memory/index.md"
LEARNINGS="$PROJECT_ROOT/.claudehut/memory/learnings.jsonl"

[[ -f "$INDEX" ]] || { echo "error: index.md not found at $INDEX" >&2; exit 2; }

# Scan main Java sources for classes by domain (package = domain)
TMP="$(mktemp)"

cat > "$TMP" <<'EOF'
# Reusable Implementation Index

> Auto-regenerated by claudehut:learn. Manual edits in custom sections are preserved
> if you mark them with `<!-- BEGIN MANUAL -->` / `<!-- END MANUAL -->`.

EOF

# Iterate top-level packages
if [[ -d "$PROJECT_ROOT/src/main/java" ]]; then
  find "$PROJECT_ROOT/src/main/java" -type d -mindepth 3 -maxdepth 5 | while read -r dir; do
    domain="$(basename "$dir")"
    # Skip common non-domain dirs
    case "$domain" in
      config|util|common|core|main|java|src) continue ;;
    esac
    classes=$(find "$dir" -maxdepth 1 -name "*.java" -type f 2>/dev/null | sort || true)
    [[ -z "$classes" ]] && continue
    echo "## Domain: $domain" >> "$TMP"
    echo "$classes" | while read -r f; do
      cls="$(basename "$f" .java)"
      # Best-effort: take first line of class-level comment
      purpose=$(awk '/\/\*\*/,/\*\//{print}' "$f" 2>/dev/null | head -3 | tail -1 | sed 's|.*\*\s*||;s|\.$||' | head -1)
      [[ -z "$purpose" ]] && purpose="<no description>"
      rel="${f#$PROJECT_ROOT/}"
      echo "- $cls → \`$rel\` — $purpose" >> "$TMP"
    done
    echo "" >> "$TMP"
  done
fi

# Preserve manual section if present in old index
if grep -q '<!-- BEGIN MANUAL -->' "$INDEX"; then
  echo "" >> "$TMP"
  awk '/<!-- BEGIN MANUAL -->/,/<!-- END MANUAL -->/' "$INDEX" >> "$TMP"
fi

mv "$TMP" "$INDEX"
echo "Reindex complete: $INDEX"
